apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-template-go
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
    - step: run-the-template
      functionRef:
        name: function-template-go
      credentials:
        - name: default
          source: Secret
          secretRef:
            namespace: default
            name: default
        - name: n1
          source: Secret
          secretRef:
            namespace: n1
            name: n1
